
'use strict';
const yeoman = require('yeoman-environment');
const path = require('path');
const TerminalAdapter = require('yeoman-environment/lib/adapter.js');
const fs = require('fs');
const semver = require('semver');
var exec = require('child_process').exec;

class CreateSuppressingTerminalAdapter extends TerminalAdapter {
  constructor() {
    super();
    // suppress 'create' output generated by yeoman
    this.log.create = function() {};
  }
}

function init(projDir, argsOrName) {
  console.log("initiating project" , projDir);
  const env = yeoman.createEnv(
    undefined,
    undefined,
    new CreateSuppressingTerminalAdapter()
  );
  env.register(
    require.resolve(path.join(__dirname, 'generator')),
    'react:app'
  );
  const args = Array.isArray(argsOrName)
    ? argsOrName
    : [argsOrName].concat(process.argv.slice(4));
  const generator = env.create('react:app', {args: args});
  generator.destinationRoot(projDir);
  generator.run();
}

init(process.cwd() , process.argv[2]);
