
'use strict';
const yeoman = require('yeoman-environment');
const path = require('path');
const TerminalAdapter = require('yeoman-environment/lib/adapter.js');
const fs = require('fs');
const semver = require('semver');

class CreateSuppressingTerminalAdapter extends TerminalAdapter {
  constructor() {
    super();
    // suppress 'create' output generated by yeoman
    this.log.create = function() {};
  }
}

function init(projDir, argsOrName) {
  console.log("initiating project" , projDir);
  const env = yeoman.createEnv(
    undefined,
    undefined,
    new CreateSuppressingTerminalAdapter()
  );
  env.register(
    require.resolve(path.join(__dirname, 'generator')),
    'react:app'
  );
  const args = Array.isArray(argsOrName)
    ? argsOrName
    : [argsOrName].concat(process.argv.slice(4));
  const generator = env.create('react:app', {args: args});
  generator.destinationRoot(projDir);
  generator.run();
  installReactNative(argsOrName);
}

function installReactNative(projName) {
  var root = path.resolve(projName);
  const packageJson = {
    name: projName,
    version: '0.0.1',
    private: 'true',
    scripts: {
      start: 'node node_modules/react-native/local-cli/cli.js start'
    }
  };
  fs.writeFileSync(path.join(process.cwd(), 'package.json'), JSON.stringify(packageJson));
}

init(process.cwd() , process.argv[2]);
